#! /bin/bash

#*****----- Workspaces -----*****
bspc monitor -d 1  2  3  4  5
#*****----- Window Gaps -----*****
bspc config gapless_monocle false
bspc config window_gap 5
#*****----- Window Borders -----*****
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 2
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"
#*****----- Fix Pointer -----*****
xsetroot -cursor_name left_ptr &

bspc config split_ratio          0.5
#*****----- BSPWM Configs -----*****
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	     true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#*****----- BSPWN Rules -----*****
# bspc rule -a feh state=floating
# bspc rule -a firefox state=floating
# bspc rule -a firefox desktop='^2' follow=on
#*****----- BSPWN Launches -----*****
sxhkd &
numlockx &
nitrogen --restore &
picom &
flameshot &
#setxkbmap -option grp:alt_shift_toggle us,ru &
~/.config/polybar/launch.sh


