#! /bin/bash
#▗▄▄▖  ▗▄▄▖▗▄▄▖ ▗▖ ▗▖▗▖  ▗▖
#▐▌ ▐▌▐▌   ▐▌ ▐▌▐▌ ▐▌▐▛▚▞▜▌
#▐▛▀▚▖ ▝▀▚▖▐▛▀▘ ▐▌ ▐▌▐▌  ▐▌
#▐▙▄▞▘▗▄▄▞▘▐▌   ▐▙█▟▌▐▌  ▐▌

#*****----- Workspaces -----*****
bspc monitor -d 1 2 3 4 5 6 &
#bspc monitor -d       &
#*****----- BSPWN Launch -----*****
sxhkd &
feh --no-fehbg --bg-fill ~/Pictures/bg.png &
picom &
telegram-desktop -startintray &
flameshot &
alsa &
copyq &
blueman-applet &
~/.config/bspwm/polybar/launch.sh &
#*****----- Window Gaps -----*****
bspc config gapless_monocle false &
bspc config window_gap 2 &
#*****----- Window Borders -----*****
bspc config focused_border_color "#43789C"
#bspc config normal_borredshift-gtkder_color "#efffff"
bspc config border_width 4 &
bspc config normal_border_color "#101010"
#bspc config presel_feedback_color "#efffff"
#*****----- Fix Pointer -----*****
xsetroot -cursor_name left_ptr &
#*****----- BSPWM Configs -----*****
bspc config focus_follows_pointer true &
bspc config pointer_modifier super &
bspc config pointer_action1 move&
bspc config pointer_action2 resize_corner &
#*****----- Key to move/resize window -----*****
bspc config pointer_modifier	super &
#*****----- I dont know why this is here, everyone putting these in their configs so i did too-----*****
bspc config single_monocle	     true &
bspc config gapless_monocle      false &
bspc config paddingless_monocle	 true &
bspc config borderless_monocle   true &
bspc config split_ratio          0.5 &

bspc config focus_follows_pointer true &

#bspc config pointer_modifier mod4
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner
#*****----- BSPWN Rules -----*****
bspc rule -a firefox center=true state=tiled &
#bspc rule -a firefox desktop='^2' follow=on
#bspc rule -a TelegramDesktop state=floating center=true follow=on rectangle=485x1000+0+0
bspc rule -a TelegramDesktop state=floating center=true rectangle=940x738 &
bspc rule -a gnome-calculator state=floating rectangle=374x488 &
bspc rule -a pavucontrol follow=on state=floating rectangle=800x400+1100+635 &
bspc rule -a Gthumb center=true follow=on state=floating&
bspc rule -a SimpleScreenRecorder center=true  follow=on state=floating&
bspc rule -a vlc follow=on center=true state=floating&
bspc rule -a file-roller follow=on center=true state=floating&
bspc rule -a copyq follow=on state=floating rectangle=500x400+1100+637&

#setxkbmap -option grp:alt_shift_toggle us,ru &
