#! /bin/bash

sxhkd &
numlockx &
nitrogen --restore &
picom --config ~/.config/bspwm/picom/picom.conf &
xsetroot -cursor_name left_ptr &
setxkbmap -option grp:alt_shift_toggle us,ru &
#polybar

pkill polybar && sleep 1
polybar &

#firefox &
#telegram-desktop -startintray &
#lutris &E

#bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+750+90
#bspc rule -a TelegramDesktop state=floating follow=off
#bspc rule -a firefox state=floating rectangle=1600x900+160+90 desktop='^1'
#bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6' 
#bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
#bspc rule -a dmenu rectangle=900x22+610+90
#bspc rule -a Viewnior rectangle=1350x900+285+90 state=floating
#bspc rule -a Inkscape desktop='^3'
#bspc rule -a Blender desktop='^2'

bspc monitor -d 1  2  3  4  5

bspc config border_width         1
bspc config window_gap          5

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"
bspc config presel_feedback_color "#23252e"

#bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
