# (Tokyo Night) color scheme for Emilia Rice

# Default colors
[colors.primary]
background = "#0E1113"
foreground = "#afb1db"

# Cursor colors
[colors.cursor]
cursor = "#bb9af7"
text = "#1a1b26"

# Normal colors
[colors.normal]
black="#45475A"   
red="#F38BA8"   
green="#A6E3A1"   
yellow="#F9E2AF"
blue="#89B4FA"   
magenta="#F5C2E7"   
cyan="#94E2D5"   
white="#BAC2DE"


# Bright colors
[colors.bright]
black="#585B70"  
red="#F38BA8"  
green="#A6E3A1"  
yellow="#F9E2AF"
blue="#89B4FA"  
magenta="#F5C2E7"  
cyan="#94E2D5"  
white="#A6ADC8"
