;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;

;include-file = ~/.cache/wal/colors-polybar.ini
include-file = ./modules.ini
include-file = ./colors.ini

[bar/mybar]
width = 100%
height = 25pt

background = ${colors.bg}
foreground = ${colors.fg}

;border-size = 5
;border-color = ${colors.bg}
padding-left = 2
padding-right = 2

module-margin = 1

separator = •
separator-foreground = ${colors.overlay0}

font-0 = "JetbrainsMono NF:size=12.5:weight=bold;3" 
;font-1 = "M Plus 1p:size=11:weight=bold;3" 

modules-left = arch memory cpu temperature battery
modules-center = bspwm date
modules-right =  wlan xkeyboard pulseaudio powermenu

# scroll-up = bspc desktop -f prev.local
# scroll-down = bspc desktop -f next.local

enable-ipc = true
wm-restack = bspwm

[settings]

#pseudo-transparency = true
