[module/round-left]
type = custom/text
content = %{T3} %{T-}
content-foreground = ${colors.blue}

[module/round-right]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.blue}

[network-base]
type = internal/network
interval = 10
format-connected = <label-connected>
format-disconnected = <label-disconnected>
format-prefix = "  "
format-prefix-foreground = ${colors.sky}
label-disconnected =  "%{A1:sh $HOME/bin/wifi:} 󰖪 %{A}" 
label-disconnected-foreground = ${colors.red}
[module/wlan]
inherit = network-base
interface-type = wireless

;format-connected-prefix = "   "
;format-disconnected-prefix = "  "
format-connected-prefix-foreground = ${colors.sky}
;format-disconnected-prefix-foreground = ${colors.red}

;label-connected = %essid% 
label-connected = "%{A1:sh $HOME/bin/wifi:}  %{A}" 
format-connected-foreground = ${colors.sky}
click-left = sh ~/bin/wifi


;[module/eth]
;inherit = network-base
;interface-type = wired
;label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/bspwm]
type = internal/xworkspaces


label-active = %name%
label-active-background = ${colors.lavender}
label-active-underline = ${colors.blue}
label-active-foreground = ${colors.bg}
label-active-padding = 1
border-radius = 15pt

label-occupied = %name%
label-occupied-padding = 1
label-occupied-foreground = ${colors.fg}

label-urgent = %name%
label-urgent-background = ${colors.red}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.surface0}
label-empty-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.blue}
format-volume = <label-volume>

label-volume = %percentage:2%%
label-volume-foreground = ${colors.blue}

label-muted =   muted
label-muted-foreground = ${colors.red}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.flamingo}
label = %percentage_used:2%%
label-foreground = ${colors.flamingo}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.peach}
label = %percentage:2%%
label-foreground = ${colors.peach}

[module/date]
type = internal/date
interval = 1
format = <label>
  
;date = %A %b, %d
;date-alt = %a, %d %b %Y%

time = %H:%M 
time-alt = %a, %d %b %Y%

label = %time%    
label-foreground = ${colors.rosewater}

[module/battery]
type = internal/battery
full-at = 98
low-at = 10

battery = BAT1
adapter = ACAD
poll-interval = 5

time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <label-low> <animation-low>

label-charging = "%percentage%% "
label-discharging = "%percentage%% "
label-full = " 100% "
label-low = "%percentage% "


ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = ""
bar-capacity-width = 10

animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
animation-charging-framerate = 910

animation-discharging-0 = " "
animation-discharging-1 = " "
animation-discharging-2 = " "
animation-discharging-3 = " "
animation-discharging-4 = " "
animation-discharging-framerate = 500

animation-low-0 = "  "
animation-low-1 = "  "
animation-low-framerate = 1500

animation-low-foreground = ${colors.red}
format-charging-foreground = ${colors.green}
label-charging-foreground = ${colors.green}
format-discharging-foreground = ${colors.red}
label-discharging-foreground = ${colors.red}
format-full-prefix-foreground = ${colors.green}
format-foreground = ${colors.foreground}
;format-background = #2b2f37
ramp-capacity-foreground =  ${colors.green}
animation-charging-foreground = ${colors.green}


[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = "  "
format-prefix-foreground = ${colors.maroon}
label-layout = %layout%
label-layout-foreground = ${colors.maroon}

label-indicator-padding = 1
label-indicator-foreground = ${colors.red}

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-warn = <ramp> <label-warn>
format-padding = 0 

label = %temperature%
label-foreground = ${colors.blue}

label-warn = %temperature%
label-warn-foreground = ${colors.red}

ramp-0 = " "
ramp-foreground = ${colors.blue}

[module/powermenu]
type = custom/text 

label = " "
label-foreground = ${colors.red}

click-left = sh ~/bin/powermenu

[module/arch]
type = custom/text 

label = " "
label-foreground = ${colors.blue}

click-left = rofi -show drun


; [module/network]
; type = internal/network
; internal = 5
;
; format-connected = <label-connected>
; format-disconnected = <label-disconnected>
; label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
; interface-type = wired
; label-connected = %{F#F0C674}%{F-} %downspeed:9%
