;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;	This config is totally mess :)
;
;==========================================================

[colors]
black=#080c0d   
red=#dd6777
green=#50fa7b 
yellow=#f1fa8c
blue=#86aaec
magenta=#c296eb   
cyan=#93cee9   
white=#f8f8f2

background = #080c0d 
;for workspaces highlight
background-alt = #86aaec
;text-color
foreground = #C5C8C6
;accent color
primary = #86aaec
disabled = #838787
[bar/example]
width = 100%
height = 24pt
radius = 3

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

;border-size = 2pt
;border-color = #000000
;border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = •
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=13;1
font-1 = JetBrainsMono Nerd Font:size=18;1
font-2 = Material Design Icons:style=Bold:size=13;1
font-3 = unifont:fontformat=truetype:size=13:antialias=true;

;xwindow
modules-left = wlan temperature memory cpu battery
modules-center = xworkspaces
modules-right = date brightness alsa xkeyboard powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = bspwm

override-redirect = false

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.white}
label-active-foreground = ${colors.background}
label-active-underline= ${colors.white}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.red}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
format-prefix = "  "
format-prefix-foreground = ${colors.primary}
label = %title:0:60:...%

;[module/fil5 minutes agoesystem]
;type = internal/fs
;interval = 25

;mount-0 = /

;label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

;label-unmounted = %mountpoint% not mounted
;label-unmounted-foreground = ${colors.disabled}


[module/powermenu]
type = custom/text 

label = " "
label-foreground = ${colors.blue}

click-left = sh ~/bin/powermenu

[module/battery]
type = internal/battery
full-at = 98
low-at = 10

battery = BAT1
adapter = ACAD
poll-interval = 5

time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <label-low> <animation-low>

label-charging = "%percentage%% "
label-discharging = "%percentage%% "
label-full = " 100% "
label-low = "%percentage% "

ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
bar-capacity-width = 10

animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
animation-charging-framerate = 910

animation-discharging-0 = " "
animation-discharging-1 = " "
animation-discharging-2 = " "
animation-discharging-3 = " "
animation-discharging-4 = " "
animation-discharging-framerate = 500

animation-low-0 = "  "
animation-low-1 = "  "
animation-low-framerate = 1500

animation-low-foreground = ${colors.red}
format-charging-foreground = ${colors.foreground}
label-charging-foreground = ${colors.foreground}
format-discharging-foreground = ${colors.foreground}
label-discharging-foreground = ${colors.foreground}
format-full-prefix-foreground = #A0E8A2
format-foreground = ${colors.foreground}
;format-background = #2b2f37
ramp-capacity-foreground =  ${colors.green}
animation-charging-foreground = ${colors.green}

[module/alsa]
type = internal/alsa
format-volume = <ramp-volume> <label-volume>
;format-volume-padding = 1
format-muted = 
format-muted-padding = 1
label-volume = %percentage%%
ramp-volume-0 = %{F#86aaec}%{F-}
ramp-volume-1 = %{F#86aaec}%{F-}
ramp-volume-2 = %{F#86aaec}%{F-}
ramp-volume-3 = %{F#86aaec}%{F-}
ramp-volume-4 = %{F#86aaec}%{F-}
ramp-volume-5 = %{F#86aaec} %{F-}
ramp-volume-6 = %{F#86aaec} %{F-}
ramp-volume-7 = %{F#86aaec} %{F-}
ramp-volume-8 = %{F#86aaec} %{F-}
ramp-volume-9 = %{F#86aaec} %{F-}
ramp-headphones-0 = 
ramp-headphones-1 = 
format-volume-foreground = ${colors.foreground}
format-muted-foreground = ${colors.red}

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 70

format = <ramp> <label>
format-warn = <ramp> <label-warn>
format-padding = 0 
label = %temperature%
label-warn = %temperature%
ramp-0 = ""
ramp-foreground = ${colors.cyan}


[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = "  "
format-prefix-foreground = ${colors.primary}
label-layout = %layout%
label-layout-foreground = ${colors.foreground}

label-indicator-padding = 1
label-indicator-foreground = ${colors.red}

[module/round-left]
type = custom/text
content = %{T3} %{T-}
content-foreground = ${colors.background}

[module/round-right]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.background}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.yellow}
label = %gb_used%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.magenta}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 10
format-connected = <label-connected>
format-disconnected = <label-disconnected>
format-prefix = "  "
format-prefix-foreground = ${colors.primary}
label-disconnected = "  "
label-disconnected-foreground = ${colors.red}

[module/wlan]
inherit = network-base
interface-type = wireless

click-left = sh ~/bin/wifi

;format-connected-prefix = "   "
;format-disconnected-prefix = "  "
format-connected-prefix-foreground = ${colors.primary}
;format-disconnected-prefix-foreground = ${colors.red}

;label-connected = %essid% 
label-connected = "  " 
format-connected-foreground = ${colors.primary}
;[module/eth]
;inherit = network-base
;interface-type = wired
;label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

 [module/time]
type = internal/date
interval = 60
format = <label>
format-background = #2b2f37
date = %{F#888e96}  %H:%M %p%{F-}
time-alt = %{F#61afef}  %a, %d %b %Y%{F-}
label = %date%%time%

[module/date]
type = internal/date
interval = 1

date = %{F#89B4FA} %{F-} %H:%M %p%
time-alt = %{F#89B4FA} %{F-} %a, %d %b %Y%

label = %date%%time%
label-foreground = ${colors.primary}

[module/brightness]
type = internal/backlight


use-actual-brightness = true

poll-interval = 0

enable-scroll = true

scroll-interval = 5
reverse-scroll = true

format = "<ramp><label>"
;format-background = ${color.} 

label = %percentage%%
;label-foreground = ${color.} 


ramp-0 = "󰃞 " 
ramp-1 = "󰃝 "
ramp-2 = "󰃟 " 
ramp-3 = "󰃠 "
ramp-foreground = ${colors.primary}


[settings]
screenchange-reload = true
pseudo-transparency = true

